# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ddb39e99f59944177840ff61d05af5180cf5af120f39acd07e4ba310ccaaf5e59c088bbf0b88b96453f9c7dbbe08c0d0ddd3d3c57c0710fe6dd03698513db92

test:
  secret_key_base: 4dd6c4a7701e321a26c8f543a3d6621f2041e1b3e40cff1b6ab53fea2fc194c6879e9b2e24deecbafadb7ae1d3d8a5b7607b94cd3962bf06dfcc64500f06a08b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
